# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 02:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ndharea',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('shape_area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('areasqkm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=2, max_digits=9)),
                ('resolution', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fdate', models.DateField()),
                ('permanent', models.CharField(db_column=b'permanent_', max_length=200)),
                ('gnis_id', models.CharField(max_length=200)),
                ('gnis_name', models.CharField(max_length=200)),
                ('ftype', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fcode', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shape_leng', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
